version: "3.7"

services:
 db:
    image: postgres:15
    container_name: db_tm
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

 app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: app_tm
    command: ["/app_tm/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
