version: "3.7"

services:
  db:
    image: postgres:15
    env_file:
      - .env-non-dev
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

#    command: -p 1221
#    expose:
#      - 1221

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
