"""fixed model task2

Revision ID: 1885e3780231
Revises: 1450834c23cb
Create Date: 2024-01-16 21:21:26.447903

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1885e3780231'
down_revision: Union[str, None] = '1450834c23cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType([
        ('create', 'Создана'),
        ('process', 'В процессе'),
        ('finish', 'Закончена'),
    ]), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
